server:
  port: 8081
spring:
  cloud:
    config:
      server:
         git:
           default-label: usuario-config-server
              uri: https://github.com/devhuitzil/Olymicroservice-curso 
              search-paths: config-data
  application:
    name: config-service
